#!/bin/sh

set -e

installDir=$1

grep '^[^#]' | while read plugin; do
    url=https://api.github.com/repos/$plugin/tarball
    curl -L $url | tar -xz -C $installDir
done

ls $installDir | sed "s#^#$installDir/#g"
