#!/bin/sh

basedir=~/dotfiles
readDir=$basedir/src/vim-config/plugins
installDir=$basedir/build/plugins-$(date +%s)
rtpDir=~/.vim.rtp

mkdir -p $installDir
mkdir -p $rtpDir

(./github2install $installDir < $readDir/common/github) > $rtpDir/common
(./github2install $installDir < $readDir/non-nix/github) > $rtpDir/non-nix
