#!/bin/sh

iwconfig wlp3s0 2>&1 | grep -q 'no wireless extensions' && {
  printf 'Conn: wired'
  exit 0
}

essid=$(iwconfig wlp3s0 | awk -F '"' '/ESSID/ {print $2}')
down=$(iwconfig 2>/dev/null | sed -nE 's/^.*Bit Rate=([^ ]+ [^ ]+).*$/\1/p')

printf 'Conn %s %s\n' "$essid" "$down"
