#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xset +fp $HOME/dotfiles/aux/fonts
xset rehash

xrdb -merge $HOME/.Xresources

# keyboard stuff
xset r rate 300 50 &

#xterm &

#xmonad

xset fp default
