# Source .bashrc if interactive
if [ -n $(echo $- | grep i) ]; then
  source $HOME/.bashrc
fi
if [ -e /Users/spinalen/.nix-profile/etc/profile.d/nix.sh ]; then
    . /Users/spinalen/.nix-profile/etc/profile.d/nix.sh
fi
