# source .bashrc if interactive
if [ -n $(echo $- | grep i) ]; then
  . $HOME/.bashrc
fi

if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then
    . $HOME/.nix-profile/etc/profile.d/nix.sh
fi

# PROVISIONAL
export VIM_PLUGIN_PATH="$(nix-build '<nixpkgs>' -A vimPlugins.youcompleteme)/share/vim-plugins/youcompleteme"
