# Determine system
# TODO add more detail (linux distro)

case "$(uname -s)" in
    Darwin)
        MY_SYSTEM=darwin
        ;;
    Linux)
        MY_SYSTEM=linux
        ;;
esac

# Bootstrap environment if necessary

if [ $MY_SYSTEM = darwin ]; then
    . $HOME/dotfiles/config/sh/darwin/*.sh
fi

# In scope:
#   MY_SYSTEM
#   MY_DOTFILES
#   MY_LOCAL
#   MY_VIM_BUNDLE
#   MY_VIM_PLUGIN_PATH

# Posix shell init

for file in $MY_DOTFILES/config/sh/*.sh; do
    . $file
done

# Prompt

reset="\[$(tput sgr0)\]"
symbol="\[$(tput setaf 2)\]"
text="\[$(tput setaf 6)\]"

if printf '%s' "$LANG" | grep -qiE 'utf-?8'; then
    lambda="λ"
    arrow="→"
else
    lambda="\\"
    arrow="->"
fi

PS1="$text \u@\h $symbol$lambda$text \w $symbol$arrow$reset "

# Fix colors in screen in X11/macOS

if [ -n "$DISPLAY" ] || [ $MY_SYSTEM = darwin ]; then
    export TERM=xterm-256color
fi

# History

HISTSIZE=100000
HISTFILESIZE=100000

# Imports

for file in $MY_DOTFILES/config/bash/fzf/*.bash; do
    . $file
done

if [ -e $MY_LOCAL/bashrc ]; then
    . $MY_LOCAL/bashrc
fi
