#!/bin/sh
(
    (
        echo "{"
        grep '^[^#]' | while read plugin; do
            url=https://github.com/$plugin
            (nix-prefetch-git $url) | sed 's/Commit[a-zA-Z0-9 -+:]\+$//g' | sed 's/git revision is //g' | (
                read rev
                read date
                read sha256
                echo "  \"$plugin\" = {"
                echo "    rev = \"$rev\";"
                echo "    sha256 = \"$sha256\";"
                echo "  };"
            )
        done
        echo "}"
    ) < ./plugins/github.txt
) > ../nix-config/nixpkgs-config/local-pkgs/lame-vim-plugins/plugins/github.nix
