#!/bin/sh
pluginList=~/dotfiles/src/vim-config/plugins.txt
gitPlugins=~/dotfiles/src/nix-config/nixpkgs-config/local-pkgs/vim-plugins/git-plugins.nix
myPlugins=~/dotfiles/src/nix-config/nixpkgs-config/aux/git-plugins.nix

(
    (
        echo "{"
        grep ^[^\#] | while read plugin; do
            url=https://github.com/$plugin
            (nix-prefetch-git $url 2> /dev/null) | sed 's/Commit[a-zA-Z0-9 -+:]\+$//g' | sed 's/git revision is //g' | (
                read rev
                read date
                read sha256
                echo "  \"$plugin\" = {"
                echo "    rev = \"$rev\";"
                echo "    sha256 = \"$sha256\";"
                echo "  };"
            )
        done
        echo "}"
    ) < $pluginList
) > $gitPlugins

(
    (
        echo "["
        grep ^[^\#] | while read plugin; do
            echo "  \"$plugin\""
        done
        echo "]"
    ) < $pluginList
) > $myPlugins
