" +-----------------------+
" | NICK SPINALE'S .vimrc |
" +-----------------------+

" TODO
"   find mapping worthy of <backspace>
"   clear autocmds before any here? (au!)?
"   deal with ftplugins messing with my options (namely fo)
"   tabular comment function
"       will improve regex to only match last comment phrase in line
"       and not match full-line comments

"   ELEGANT RUNTIMEPATH
"       as list: let &runtimepath = join(myrtp, ',')
"       order: $VIMRUNTIME, ./vim, plugins

let s:nice_rtp = [ '$VIMRUNTIME', expand('<sfile>:h') . 'vim' ]

if system('uname -a') =~ 'NixOS'
  let s:plugin_lists = [ '/run/current-system/sw/share/vim-plugins/lame.rtp'
                     \ , '/run/current-system/sw/share/vim-plugins/annoying.rtp'
                     \ ]
else
  let s:plugin_lists = [ '~/.vimrc.rc' ]
endif

function g:Mapped(fn, l)
  let new_list = deepcopy(a:l)
  call map(new_list, string(a:fn) . '(v:val)')
  return new_list
endfunction

function g:Concat(xss)
  let ys = []
  for xs in a:xss
    let ys += xs
  endfor
  return ys
endfunction

let &rtp = join(s:nice_rtp + g:Concat(g:Mapped(function('readfile'), s:plugin_lists)), ',')

let g:vimrcDir = "$HOME/dotfiles/src/vim-config/vimrc.d/"

set nocompatible

noremap <space> <nop>
noremap <del> <nop>
noremap <bs> <nop>
noremap <cr> <nop>
noremap Y <nop>

let s:imports = [ 'abbreviations'
              \ , 'appearance'
              \ , 'buffers'
              \ , 'controls'
              \ , 'editing'
              \ , 'editor'
              \ , 'proc'
              \ , 'toggles'
              \ , 'misc'
              \ ]

for import in s:imports
  exec 'source ' . g:vimrcDir . 'modules/' . import . '.vim'
endfor
