" +-----------------------+
" | NICK SPINALE'S .vimrc |
" +-----------------------+

" TODO
"   find mapping worthy of <backspace>
"   clear autocmds before any here? (au!)?
"   deal with ftplugins messing with my options (namely fo)
"   tabular comment function
"       will improve regex to only match last comment phrase in line
"       and not match full-line comments

"   ELEGANT RUNTIMEPATH
"       as list: let &runtimepath = join(myrtp, ',')
"       order: $VIMRUNTIME, ./vim, plugins

set nocompatible
filetype plugin indent on

" let g:vim_config_dir = expand('<sfile>:h')
let g:vim_config_dir = expand('~/dotfiles/src/vim-config/')

for f in split(glob(g:vim_config_dir . 'vimrc.d/lib/*'))
  exec 'source '.f
endfor

if system('uname -a') =~ 'NixOS'
  let s:plugin_lists = [ '/run/current-system/sw/share/vim-plugins/lame.rtp'
                     \ , '/run/current-system/sw/share/vim-plugins/annoying.rtp'
                     \ ]
else
  let s:plugin_lists = [ '~/.vimrc.rc' ]
endif

let s:nice_rtp = [ expand('$VIMRUNTIME'), g:vim_config_dir.'vim' ]

let s:all_rtp = s:nice_rtp + g:Concat(g:Mapped(function('readfile'), s:plugin_lists))

let &rtp = join(s:all_rtp, ',')
" exec 'set rtp+='.join(s:all_rtp, ',')

noremap <space> <nop>
noremap <del> <nop>
noremap <bs> <nop>
noremap <cr> <nop>
noremap Y <nop>

for f in split(glob(g:vim_config_dir . 'vimrc.d/modules/*'))
  exec 'source '.f
endfor
