#!/bin/sh

basedir=~/dotfiles
readDir=$basedir/src/vim-config/plugins
installDir=$basedir/build/plugins-$(date | sha256sum | head -c 8)
rtpFile=~/.vimrc.rtp

mkdir -p $installDir

set -e

(
    (
        grep '^[^#]' | while read plugin; do
            url=https://api.github.com/repos/$plugin/tarball
            curl -L $url | tar -xz -C $installDir
        done
        ls $installDir | sed "s#^#$installDir/#g"
    ) < $readDir/github.txt
) > $rtpFile
