#!/bin/sh
basedir="$HOME/dotfiles"

while read line; do
    read link target <<< $(echo $line | awk '{ print $1; print $2; }')
    mkdir -p $(dirname $target)
    ln -sfnv $basedir/src/$link $target
done
