#!/bin/sh

# becuase readlink -m is nonstandard.
# dotfiles="$(python -c "from os.path import dirname, abspath; print dirname(dirname(abspath('$0')))")"
dotfiles="$(dirname "$(cd "$(dirname "$0")" && pwd)")"

(while read line; do
    read link target <<< $(echo $line | awk '{ print $1; print $2; }')
    mkdir -p $HOME/$(dirname $target)
    cmd="ln -sfnv $dotfiles/config/$link $HOME/$target"
    echo "$cmd"
    $cmd
done) < $(dirname $0)/$1
