#!/bin/sh

(while read line; do
    read link target <<< $(echo $line | awk '{ print $1; print $2; }')
    mkdir -p $HOME/$(dirname $target)
    cmd="ln -sfnv $CFGDIR/dotfiles/config/$link $HOME/$target"
    echo "$cmd"
    $cmd
done) < $(dirname $0)/$1
