#!/bin/sh

BOOTSTRAPPED_CFGDIR="$(dirname $(dirname $(dirname $(readlink -m $0))))"
echo $BOOTSTRAPPED_CFGDIR

(while read line; do
    read link target <<< $(echo $line | awk '{ print $1; print $2; }')
    mkdir -p $HOME/$(dirname $target)
    cmd="ln -sfnv $BOOTSTRAPPED_CFGDIR/dotfiles/config/$link $HOME/$target"
    echo "$cmd"
    $cmd
done) < $(dirname $0)/$1
